const $=id=>document.getElementById(id), key='college-bulk-v1';
let saved;try{saved=JSON.parse(localStorage.getItem(key)||'{}');}catch{saved={};}
let foods=Array.isArray(saved.items)?saved.items:[],plan=null;
const today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Los_Angeles',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
$('date').value=saved.date||today;
const defaults=[['breakfast','07:00','11:00'],['lunch','11:30','14:00'],['dinner','17:00','20:00']];
for(const [period,start,end] of defaults){const div=document.createElement('div');div.className='window';div.dataset.period=period;div.innerHTML=`<label><input type="checkbox" class="confirmed"> ${period} · hours confirmed</label><div class="pair"><label>From<input class="start" type="time" value="${start}" required></label><label>Until<input class="end" type="time" value="${end}" required></label></div><label>Visit<select class="mode"><option value="dine-in">Dine in · 30 minutes</option><option value="eco-box">Eco-Box · 10 minutes</option></select></label>`;$('windows').append(div);const old=saved.meals?.find(m=>m.period===period);if(old){div.querySelector('.start').value=old.start;div.querySelector('.end').value=old.end;div.querySelector('.mode').value=old.mode;div.querySelector('.confirmed').checked=old.confirmedHours===true;}}
for(const id of ['calories','protein','eggs','dairy','ecoAvailable','ecoPaid'])if(saved[id]!==undefined){if($(id).type==='checkbox')$(id).checked=saved[id];else $(id).value=saved[id]||'';}
$('travel').value=saved.travelMinutes??15;$('allergens').value=(saved.allergens||[]).join(', ');$('busy').value=(saved.busy||[]).map(b=>`${b.start}-${b.end}`).join('\n');
const split=s=>s.split(',').map(a=>a.trim().toLowerCase()).filter(Boolean);
function read(){return {date:$('date').value,calories:Number($('calories').value),protein:Number($('protein').value),eggs:$('eggs').checked,dairy:$('dairy').checked,ecoAvailable:$('ecoAvailable').checked,ecoPaid:$('ecoPaid').checked,allergens:split($('allergens').value),travelMinutes:Number($('travel').value),busy:$('busy').value.split('\n').filter(s=>s.trim()).map(s=>{const [start,end]=s.trim().split('-').map(v=>v.trim());return {start,end};}),meals:[...document.querySelectorAll('.window')].map(d=>({period:d.dataset.period,start:d.querySelector('.start').value,end:d.querySelector('.end').value,mode:d.querySelector('.mode').value,confirmedHours:d.querySelector('.confirmed').checked})),items:foods};}
function persist(){try{localStorage.setItem(key,JSON.stringify(read()));}catch{$('notice').textContent='Browser storage unavailable. Export your plan before closing.';}}
function invalidate(){plan=null;$('export').disabled=true;$('plan').replaceChildren();const p=document.createElement('p');p.className='muted';p.textContent='Settings changed. Build your day to update the plan.';$('plan').append(p);}
function renderFoods(){const date=$('date').value;$('foods').replaceChildren();const current=foods.filter(f=>f.date===date);$('emptyFoods').hidden=current.length>0;for(const f of current){const li=document.createElement('li'),text=document.createElement('span'),small=document.createElement('small'),remove=document.createElement('button');text.textContent=f.name;small.textContent=`${f.period} · ${f.serving} · ${f.calories} kcal · ${f.protein}g protein`;text.append(small);remove.textContent='Remove';remove.onclick=()=>{foods=foods.filter(x=>x!==f);persist();renderFoods();invalidate();};li.append(text,remove);$('foods').append(li);}const [y,m,d]=date.split('-');const url=new URL('https://nutrition.sa.ucsc.edu/shortmenu.aspx');url.search=new URLSearchParams({locationNum:'40',dtdate:`${Number(m)}/${Number(d)}/${y}`,sName:'UC Santa Cruz Dining',locationName:'John R. Lewis & College Nine Dining Hall',naFlag:'1',WeeksMenus:"UCSC - This Week's Menus",myaction:'read'});$('menuLink').href=url.href;}
$('settings').addEventListener('change',()=>{persist();invalidate();renderFoods();});
$('date').addEventListener('change',()=>{document.querySelectorAll('.confirmed').forEach(x=>x.checked=false);$('ecoAvailable').checked=false;$('menuStatus').textContent='No live menu loaded for this date.';persist();});
$('suggest').onclick=()=>{const w=Number($('weight').value);if(w>=25&&w<=300){$('protein').value=Math.round(w*1.6);persist();invalidate();}else $('notice').textContent='Enter a body weight from 25 to 300 kg.';};
$('foodForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);foods.push({date:$('date').value,name:f.get('name').trim(),period:f.get('period'),kind:f.get('kind'),serving:f.get('serving'),calories:Number(f.get('calories')),protein:Number(f.get('protein')),diet:f.get('diet'),eggs:f.has('eggs'),dairy:f.has('dairy'),allergens:split(f.get('allergens')),verified:f.has('verified'),source:$('menuLink').href});persist();renderFoods();invalidate();e.target.reset();};
$('refresh').onclick=async()=>{const button=$('refresh'),date=$('date').value;button.disabled=true;$('menuStatus').textContent='Checking UCSC…';try{const r=await fetch(`/api/menu?date=${encodeURIComponent(date)}`),data=await r.json();if(date===$('date').value)$('menuStatus').textContent=data.message||data.error;}catch{$('menuStatus').textContent='Could not connect. Start the local server and retry.';}finally{button.disabled=false;}};
function element(tag,text,className){const e=document.createElement(tag);e.textContent=text;if(className)e.className=className;return e;}
function renderPlan(){const root=$('plan');root.replaceChildren();const stats=element('div','','stats');stats.append(element('div',`${Math.round(plan.calories)} / ${plan.targets.calories} kcal planned`),element('div',`${Math.round(plan.protein)} / ${plan.targets.protein} g protein planned`));root.append(stats);let eaten={calories:0,protein:0};const consumed=element('p','Eaten: 0 kcal · 0 g protein','muted');root.append(consumed);for(const meal of plan.meals){const card=element('article','','meal');card.append(element('h3',`${meal.start} · ${meal.period}`),element('p',`${meal.location} · ${meal.mode==='eco-box'?'Pick up to go':'Dine in'} · visit ends ${meal.end}`));const list=element('ul','');for(const f of meal.foods)list.append(element('li',`${f.quantity} × ${f.name} (${f.serving}) — ${f.calories*f.quantity} kcal, ${Math.round(f.protein*f.quantity)} g protein`));card.append(list);const label=element('label',''),check=document.createElement('input');check.type='checkbox';check.onchange=()=>{const sign=check.checked?1:-1;eaten.calories+=sign*meal.calories;eaten.protein+=sign*meal.protein;consumed.textContent=`Eaten: ${Math.round(eaten.calories)} kcal · ${Math.round(eaten.protein)} g protein. Still needed: ${Math.max(0,plan.targets.calories-Math.round(eaten.calories))} kcal · ${Math.max(0,plan.targets.protein-Math.round(eaten.protein))} g protein.`;};label.append(check,document.createTextNode('I ate these portions'));card.append(label);root.append(card);}root.append(element('p',`Unfilled target: ${Math.round(plan.remaining.calories)} kcal · ${Math.round(plan.remaining.protein)} g protein. Add verified options or adjust portions; this planner does not invent a snack to close the gap.`,'muted'));const warnings=element('ul','','warnings');plan.warnings.forEach(w=>warnings.append(element('li',w)));root.append(warnings);}
$('settings').onsubmit=async e=>{e.preventDefault();persist();try{const r=await fetch('/api/plan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(read())});const data=await r.json();if(!r.ok)throw new Error(data.error);plan=data;renderPlan();$('export').disabled=false;$('notice').textContent='Plan updated. These are planned portions; tick a meal only after you eat it.';}catch(err){$('notice').textContent=err.message;}};
$('export').onclick=()=>{if(!plan)return;const url=URL.createObjectURL(new Blob([JSON.stringify(plan,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`alvis-meals-${plan.date}.json`;a.click();URL.revokeObjectURL(url);};
$('clear').onclick=()=>{if(confirm('Clear your targets, schedule and saved foods from this browser?')){localStorage.removeItem(key);location.reload();}};
$('calendarImport').onclick=async()=>{const button=$('calendarImport'),date=$('date').value;button.disabled=true;try{const r=await fetch(`/api/calendar?date=${encodeURIComponent(date)}`),data=await r.json();if(!r.ok)throw new Error(data.error);if(date!==$('date').value)return;$('calendarStatus').textContent=data.message+(data.syncedAt?` Last read: ${new Date(data.syncedAt).toLocaleString()}`:'');if(data.status==='live'||data.status==='snapshot'){const manual=$('busy').value.split('\n').filter(Boolean);const combined=new Set([...manual,...data.busy.map(b=>`${b.start}-${b.end}`)]);$('busy').value=[...combined].join('\n');$('cafe').replaceChildren();for(const event of data.busy.filter(b=>/baskin/i.test(b.location||''))){const p=element('p',`After ${event.end}: Perk at Baskin is a nearby café candidate. Check opening hours and a vegetarian option; main meals stay at C9.`);const a=element('a','Check Perk hours & details ↗');a.href='https://dining.ucsc.edu/locations-hours/perk-baskin/';a.target='_blank';a.rel='noreferrer';p.append(a);$('cafe').append(p);}persist();invalidate();}}catch(err){$('calendarStatus').textContent=err.message;}finally{button.disabled=false;}};
$('date').addEventListener('change',()=>{$('calendarStatus').textContent='Import availability for this date. Review and replace any old busy times.';$('cafe').replaceChildren();$('busy').value='';persist();});
renderFoods();

