import test from 'node:test';
import assert from 'node:assert/strict';
import {getDaySchedule,getServingStatus,formatClock} from './dining-hours.mjs';
const at=(iso)=>new Date(iso);
test('C9 Tuesday dinner transitions into late night',()=>{const dinner=getServingStatus('2026-10-06','40',at('2026-10-07T01:15:00Z'));assert.equal(dinner.state,'open');assert.equal(dinner.label,'Dinner');assert.equal(dinner.end,'20:00');assert.equal(dinner.next.name,'Late Night');});
test('C9 Monday has no late night',()=>{const s=getDaySchedule('2026-10-05','40');assert.equal(s.at(-1).name,'Dinner');});
test('C9 Saturday starts with brunch',()=>assert.equal(getDaySchedule('2026-10-03','40')[0].name,'Brunch'));
test('Cowell and Oakes have Sunday late night',()=>{assert.equal(getDaySchedule('2026-10-04','05').at(-1).name,'Late Night');assert.equal(getDaySchedule('2026-10-04','30').at(-1).name,'Late Night');});
test('Crown and Kresge are closed on regular weekend schedule',()=>{assert.deepEqual(getDaySchedule('2026-10-03','20'),[]);assert.deepEqual(getDaySchedule('2026-10-04','25'),[]);});
test('Kresge weekday dinner ends at 7 PM',()=>assert.equal(getDaySchedule('2026-10-05','25').at(-1).end,'19:00'));
test('continuous dining is explicitly limited',()=>{const s=getServingStatus('2026-10-06','40',at('2026-10-06T18:10:00Z'));assert.equal(s.state,'limited');assert.equal(s.label,'Continuous Dining');});
test('unknown cafe hours are not guessed',()=>assert.equal(getServingStatus('2026-10-02','23').state,'unknown'));
test('UCSD 64 Degrees uses its official weekly hours',()=>{assert.deepEqual(getDaySchedule('2026-10-08','ucsd-64-degrees'),[{name:'Open',start:'07:00',end:'23:00',limited:false}]);assert.deepEqual(getDaySchedule('2026-10-10','ucsd-64-degrees'),[{name:'Open',start:'09:00',end:'21:00',limited:false}]);});
test('UCSD overnight markets preserve early-morning service',()=>{const schedule=getDaySchedule('2026-10-08','ucsd-goodys');assert.equal(schedule[0].start,'00:00');assert.equal(schedule[0].end,'02:00');assert.equal(schedule[1].start,'07:00');});
test('UCSB dining commons use breakfast lunch dinner weekdays and brunch weekends',()=>{const weekday=getDaySchedule('2026-10-09','ucsb-portola');assert.deepEqual(weekday.map(x=>x.name),['Breakfast','Lunch','Dinner']);assert.equal(weekday[0].start,'07:15');assert.equal(weekday.at(-1).end,'20:30');assert.deepEqual(getDaySchedule('2026-10-10','ucsb-carrillo').map(x=>x.name),['Brunch','Dinner']);});
test('UCSB Ortega is weekday takeout and closed weekends',()=>{assert.deepEqual(getDaySchedule('2026-10-09','ucsb-ortega').map(x=>x.name),['Lunch','Dinner']);assert.deepEqual(getDaySchedule('2026-10-10','ucsb-ortega'),[]);});
test('snapshot schedules can drive serving state for campus adapters',()=>{const schedule=[{name:'Lunch',start:'11:00',end:'15:00'}];const s=getServingStatus('2026-10-09','future-campus',at('2026-10-09T20:00:00Z'),schedule);assert.equal(s.state,'open');assert.equal(s.label,'Lunch');assert.equal(s.end,'15:00');});
test('clock formatting is readable',()=>{assert.equal(formatClock('08:00'),'8 AM');assert.equal(formatClock('11:30'),'11:30 AM');assert.equal(formatClock('20:00'),'8 PM');});
